import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'แดชบอร์ด',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['dashboard:view'],
        subMenu: [],
    },
    {
        key: 'members',
        path: '/members',
        title: 'จัดการสมาชิก',
        translateKey: 'nav.members',
        icon: 'members',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['member:view'],
        subMenu: [],
    },
    {
        key: 'branches',
        path: '/branches',
        title: 'จัดการสาขา',
        translateKey: 'nav.branches',
        icon: 'branches',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['branch:view'],
        subMenu: [],
    },
    {
        key: 'products',
        path: '',
        title: 'จัดการสินค้า',
        translateKey: 'nav.products',
        icon: 'products',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['product:view'],
        subMenu: [
             {
                key: 'products.categories',
                path: '/products/categories',
                title: 'หมวดหมู่สินค้า',
                translateKey: 'nav.products.categories',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['product:view'],
                subMenu: [],
            },
            {
                key: 'products.list',
                path: '/products',
                title: 'สินค้าหลัก',
                translateKey: 'nav.products.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['product:view'],
                subMenu: [],
            },
            {
                key: 'products.branchProducts',
                path: '/products/branch-products',
                title: 'สินค้าสาขา',
                translateKey: 'nav.products.branchProducts',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['product:view'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'promotions',
        path: '/promotions',
        title: 'จัดการโปรโมชั่น',
        translateKey: 'nav.promotions',
        icon: 'promotions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['promotion:view'],
        subMenu: [],
    },
    {
        key: 'stock',
        path: '',
        title: 'จัดการ Stock',
        translateKey: 'nav.stock',
        icon: 'stock',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['stock:view'],
        subMenu: [
            {
                key: 'stock.requisition',
                path: '/stock/requisition',
                title: 'รายการขอเบิกสินค้า',
                translateKey: 'nav.stock.requisition',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['stock:view'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'costCalculation',
        path: '',
        title: 'คำนวณยอดขาย',
        translateKey: 'nav.costCalculation',
        icon: 'costCalculation',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['cost:view'],
        subMenu: [
            {
                key: 'costCalculation.ingredients',
                path: '/cost/ingredients',
                title: 'จัดการวัตถุดิบ',
                translateKey: 'nav.costCalculation.ingredients',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ingredient:view'],
                subMenu: [],
            },
            {
                key: 'costCalculation.productCost',
                path: '/cost/product-cost',
                title: 'คำนวณต้นทุนสินค้า',
                translateKey: 'nav.costCalculation.productCost',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['cost:view'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'broadcast',
        path: '/broadcast',
        title: 'ส่ง Broadcast',
        translateKey: 'nav.broadcast',
        icon: 'broadcast',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['broadcast:view'],
        subMenu: [],
    },
    {
        key: 'staffManagement',
        path: '/staff-management',
        title: 'จัดการพนักงาน',
        translateKey: 'nav.staffManagement',
        icon: 'staffManagement',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['staff:view'],
        subMenu: [],
    },
    {
        key: 'permissions.groups',
        path: '/permissions/groups',
        title: 'จัดการสิทธิ์',
        translateKey: 'nav.permissions',
        icon: 'permissions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['permission:view'],
        subMenu: [],
    },
]

export default navigationConfig
