import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'แดชบอร์ด',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'members',
        path: '/members',
        title: 'จัดการสมาชิก',
        translateKey: 'nav.members',
        icon: 'members',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'branches',
        path: '/branches',
        title: 'จัดการสาขา',
        translateKey: 'nav.branches',
        icon: 'branches',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'products',
        path: '/products',
        title: 'จัดการสินค้า',
        translateKey: 'nav.products',
        icon: 'products',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'stock',
        path: '',
        title: 'จัดการ Stock',
        translateKey: 'nav.stock',
        icon: 'stock',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'stock.requisition',
                path: '/stock/requisition',
                title: 'ใบเบิกสินค้า',
                translateKey: 'nav.stock.requisition',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'stock.withdraw',
                path: '/stock/withdraw',
                title: 'เบิกสินค้า',
                translateKey: 'nav.stock.withdraw',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'stock.receive',
                path: '/stock/receive',
                title: 'รับสินค้า',
                translateKey: 'nav.stock.receive',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'stock.deduction',
                path: '/stock/deduction',
                title: 'ตัดสต็อก',
                translateKey: 'nav.stock.deduction',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'broadcast',
        path: '/broadcast',
        title: 'ส่ง Broadcast',
        translateKey: 'nav.broadcast',
        icon: 'broadcast',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
